spring:
  application:
    name: approval-system
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/approval_system_dev}
    username: ${DB_USERNAME:approval_user}
    password: ${DB_PASSWORD:approval_password}
    driver-class-name: org.postgresql.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:brotherhood-approval-system-secret-key-change-in-production}
      expiration: ${JWT_EXPIRATION:3600}
      
  # Encryption Configuration
  encryption:
    key: ${ENCRYPTION_KEY:brotherhood-encryption-key-change-in-production}
    
  # Web Configuration
  web:
    resources:
      add-mappings: false
  
  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 50MB
      file-size-threshold: 2KB

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.brotherhood.approval: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# File Storage Configuration
file:
  upload-dir: ${UPLOAD_DIR:./uploads}
  max-size: 10485760  # 10MB in bytes

