spring:
  # Development Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/approval_system_dev
    username: postgres
    password: postgres
    
  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          
  # Flyway Configuration for Development
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  # Security Configuration for Development
  security:
    jwt:
      secret: dev-jwt-secret-key-change-in-production-this-should-be-at-least-256-bits-long
      expiration: 3600 # 1 hour in seconds
      
  # Encryption Configuration for Development
  encryption:
    key: dev-encryption-key-change-in-production

# Logging Configuration for Development
logging:
  level:
    com.brotherhood.approval: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG

# Development Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

