spring:
  # Railway PostgreSQL 사용 (DatabaseConfig.java에서 DataSource 설정)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC
    open-in-view: false
        
  flyway:
    enabled: false
    
  sql:
    init:
      mode: never
        
  security:
    jwt:
      secret: ${JWT_SECRET:brotherhood-approval-system-secret-key-change-in-production-2024}
      expiration: 86400000 # 24 hours
      
  # CORS 설정
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      
server:
  port: ${PORT:8080}

# Management & Actuator 설정
management:
  metrics:
    enable:
      jvm: false
      process: false
      system: false
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  
logging:
  level:
    com.brotherhood.approval: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.boot: INFO
