spring:
  # Railway PostgreSQL 사용
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/approval_system}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC
    open-in-view: false
        
  flyway:
    enabled: false
    
  sql:
    init:
      mode: never
        
  security:
    jwt:
      secret: ${JWT_SECRET:brotherhood-approval-system-secret-key-change-in-production-2024}
      expiration: 86400000 # 24 hours
      
  # CORS 설정
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      
server:
  port: ${PORT:8080}
  
logging:
  level:
    com.brotherhood.approval: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.boot: INFO
