spring:
  profiles:
    active: prod
  
  # H2 인메모리 데이터베이스 사용 (Railway 환경)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: false
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        show_sql: false
        
  flyway:
    enabled: false
    
  sql:
    init:
      mode: never
        
  security:
    jwt:
      secret: ${JWT_SECRET:brotherhood-approval-system-secret-key-change-in-production-2024}
      expiration: 86400000 # 24 hours
      
  # CORS 설정
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      
server:
  port: ${PORT:8080}
  
logging:
  level:
    com.brotherhood.approval: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.boot: INFO
