name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Build
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; ./gradlew clean build -x test; fi
      - name: Test
        run: |
          if [ -f ./gradlew ]; then ./gradlew test; elif [ -f package.json ]; then npm ci && npm test --if-present; else echo "No tests found" && exit 1; fi


